defaults:
  - GradDiff

handler: SimNPO
method_args:
  delta: 0.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  beta: 4.5
  preferences: [0.125, 1.0] # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  retain_loss_type: NLL

