# @package eval.tofu.metrics.mia_min_k
defaults:
  - ../../data/datasets@datasets: TOFU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: 32
handler: mia_min_k
k: 0.4

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.tofu.forget_split}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.tofu.holdout_split}